name: ML
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - contourpy=1.3.3
  - cpython=3.13.11
  - cycler=0.12.1
  - deprecated=1.3.1
  - donfig=0.8.1.post1
  - filelock=3.20.0
  - fmt=12.0.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - fsspec=2025.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-crc32c=1.7.1
  - jinja2=3.1.6
  - joblib=1.5.3
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcxx=21.1.7
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.6.1
  - nomkl=1.0
  - numcodecs=0.16.5
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.18.0
  - packaging=25.0
  - pandas=2.3.3
  - pillow=12.0.0
  - pip=25.3
  - pthread-stubs=0.4
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pyparsing=3.2.5
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.13
  - pytorch=2.9.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wrapt=1.17.3
  - xarray=2025.12.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zarr=3.1.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/ML
